{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1052.0 (23.12)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Chemin_Dossier\",\"Modele_Commandes\",\"Commandes\",\"Detail_Commande\",\"Categories\",\"Clients\",\"Employes\",\"Fournisseurs\",\"Produits\",\"Region\",\"_Dim_Date\",\"_Mesures\",\"Choix_HTML_Rank\",\"Choix_CAT_PDT_CLT\",\"Table_couleurs\",\"Z_PY🐍_Produits\",\"Z_PY🐍_Categories\",\"Z_PY🐍_Employes\",\"Z_PY🐍_Clients\",\"Z_PY🐍_Fournisseurs\",\"Z_PY🐍_Region\",\"Z_PY🐍_Detail_Commandes\",\"Blank_Html\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"CalcGroup\",\"DevMode\"]"
      }
    ],
    "culture": "fr-FR",
    "cultures": [
      {
        "name": "fr-FR",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "expressions": [
      {
        "name": "Modele_Commandes",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "(Nom_Fichier)=>",
          "",
          "let",
          "    Source = Excel.Workbook(File.Contents(Chemin_Dossier & \"\\Commandes\\\" & Nom_Fichier), null, true),",
          "    Feuil1_Sheet = Source{[Item=\"Feuil1\",Kind=\"Sheet\"]}[Data],",
          "    #\"En-têtes promus\" = Table.PromoteHeaders(Feuil1_Sheet, [PromoteAllScalars=true]),",
          "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"OrderID\", Int64.Type}, {\"CustomerID\", type text}, {\"EmployeeID\", Int64.Type}, {\"OrderDate\", type datetime}, {\"RequiredDate\", type datetime}, {\"ShippedDate\", type datetime}, {\"ShipVia\", Int64.Type}, {\"Freight\", type number}, {\"ShipName\", type text}, {\"ShipAddress\", type text}, {\"ShipCity\", type text}, {\"ShipRegion\", type text}, {\"ShipPostalCode\", type text}, {\"ShipCountry\", type text}}),",
          "    #\"Autres colonnes supprimées\" = Table.SelectColumns(#\"Type modifié\",{\"OrderID\", \"CustomerID\", \"EmployeeID\", \"OrderDate\", \"RequiredDate\", \"ShippedDate\", \"ShipVia\", \"Freight\", \"ShipCountry\"})",
          "in",
          "    #\"Autres colonnes supprimées\""
        ],
        "kind": "m",
        "lineageTag": "635c1892-600f-4824-b560-b05a2bec09c6"
      },
      {
        "name": "Chemin_Dossier",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": "\"C:\\Users\\Frédéric ROUCHER\\OneDrive - KPI Consulting\\Bureau\\DATASET\\\" meta [IsParameterQuery=true, List={\"C:\\Users\\Frédéric ROUCHER\\OneDrive - KPI Consulting\\Bureau\\DATASET\\\", \"Z:\\\"}, DefaultValue=\"C:\\Users\\Frédéric ROUCHER\\OneDrive - KPI Consulting\\Bureau\\DATASET\\\", Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "67ba9843-2e10-4d41-b527-daa313c98696",
        "queryGroup": "Parameters"
      }
    ],
    "perspectives": [
      {
        "name": "A1",
        "tables": [
          {
            "name": "Clients",
            "columns": [
              {
                "name": "CompanyName"
              },
              {
                "name": "Region"
              }
            ]
          },
          {
            "name": "Categories",
            "columns": [
              {
                "name": "CategoryName"
              },
              {
                "name": "Description"
              },
              {
                "name": "Regroupement"
              }
            ]
          }
        ]
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Parameters"
      }
    ],
    "relationships": [
      {
        "name": "fb3ffb8e-5be6-4136-a435-99a11f090e38",
        "fromColumn": "OrderID",
        "fromTable": "Detail_Commande",
        "toColumn": "OrderID",
        "toTable": "Commandes"
      },
      {
        "name": "feae9073-3a91-43a7-9af3-7fcc22fabf6c",
        "fromColumn": "CustomerID",
        "fromTable": "Commandes",
        "toColumn": "CustomerID",
        "toTable": "Clients"
      },
      {
        "name": "8e005ffd-3549-4a8a-b91f-2358f3cd4bd4",
        "fromColumn": "EmployeeID",
        "fromTable": "Commandes",
        "toColumn": "EmployeeID",
        "toTable": "Employes"
      },
      {
        "name": "a2f6655c-ea85-4e19-a8fd-554434c94db7",
        "fromColumn": "ProductID",
        "fromTable": "Detail_Commande",
        "toColumn": "ProductID",
        "toTable": "Produits"
      },
      {
        "name": "cd2866ce-0a05-4c40-8979-7507d8514392",
        "fromColumn": "CategoryID",
        "fromTable": "Produits",
        "toColumn": "CategoryID",
        "toTable": "Categories"
      },
      {
        "name": "88dc216c-31d6-4140-8850-08e80ac6612f",
        "fromColumn": "SupplierID",
        "fromTable": "Produits",
        "toColumn": "SupplierID",
        "toTable": "Fournisseurs"
      },
      {
        "name": "4cd2fa62-4deb-41a3-ab50-45f6fc4e3f8a",
        "fromColumn": "Region",
        "fromTable": "Clients",
        "toColumn": "Code_region",
        "toTable": "Region"
      },
      {
        "name": "ae3254ee-1f8a-4bb6-9a11-41dc52fea998",
        "fromColumn": "OrderDate",
        "fromTable": "Commandes",
        "toColumn": "Date",
        "toTable": "_Dim_Date"
      },
      {
        "name": "e72e457f-cb95-4cb9-860b-733fb705edff",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "Tri",
        "fromTable": "Choix_CAT_PDT_CLT",
        "toColumn": "Tri",
        "toTable": "Choix_HTML_Rank"
      },
      {
        "name": "352f3a8f-c3a7-4a3c-b452-1eea128cf328",
        "fromColumn": "CategoryID",
        "fromTable": "Z_PY🐍_Produits",
        "toColumn": "CategoryID",
        "toTable": "Z_PY🐍_Categories"
      },
      {
        "name": "89ab68b2-22f0-44d8-ab89-ce31b8f2cad2",
        "fromColumn": "Region",
        "fromTable": "Z_PY🐍_Clients",
        "toColumn": "Code_region",
        "toTable": "Z_PY🐍_Region"
      },
      {
        "name": "15a54d4c-1a8a-44dd-b9cb-636d0b6f71a4",
        "fromColumn": "ProductID",
        "fromTable": "Z_PY🐍_Detail_Commandes",
        "toColumn": "ProductID",
        "toTable": "Z_PY🐍_Produits"
      },
      {
        "name": "36dc24b9-5a6e-4186-8e47-1a77473805e8",
        "fromColumn": "SupplierID",
        "fromTable": "Z_PY🐍_Produits",
        "toColumn": "SupplierID",
        "toTable": "Z_PY🐍_Fournisseurs"
      }
    ],
    "sourceQueryCulture": "fr-FR",
    "tables": [
      {
        "name": "Commandes",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2fe6ea86-9217-4439-a120-98b55df01f24",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "OrderID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5c191370-0845-47f3-90b8-98e4153cc134",
            "sourceColumn": "OrderID",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd388386-dba8-40ac-8d73-fb1f85386060",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none"
          },
          {
            "name": "EmployeeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "014896eb-1b36-41f6-883a-5aeb88b52f3f",
            "sourceColumn": "EmployeeID",
            "summarizeBy": "none"
          },
          {
            "name": "OrderDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "5a9fa0d7-2911-4560-ad1e-3bdd813a4915",
            "sourceColumn": "OrderDate",
            "summarizeBy": "none"
          },
          {
            "name": "RequiredDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a2ed9b3c-bd58-48e6-a1bd-8873dbbb7088",
            "sourceColumn": "RequiredDate",
            "summarizeBy": "none"
          },
          {
            "name": "ShippedDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "d57afa8b-099d-49ac-9fb0-078100ce9d95",
            "sourceColumn": "ShippedDate",
            "summarizeBy": "none"
          },
          {
            "name": "ShipVia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "06d5be6e-7099-42d7-8b59-6c460ae219c1",
            "sourceColumn": "ShipVia",
            "summarizeBy": "sum"
          },
          {
            "name": "Freight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "308459ec-348f-4d7a-92e1-2ab3254bbdf0",
            "sourceColumn": "Freight",
            "summarizeBy": "sum"
          },
          {
            "name": "ShipCountry",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b0edb696-a54f-4ace-ab5e-7e94a1cdb775",
            "sourceColumn": "ShipCountry",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "692b6c34-bfa2-40a9-92a0-e1b6a90f8ca6",
        "partitions": [
          {
            "name": "Commandes-6698dc37-c64b-47c8-a865-94effd6141ee",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(\"C:\\Users\\Frédéric ROUCHER\\OneDrive - KPI Consulting\\Bureau\"),",
                "    #\"Lignes filtrées\" = Table.SelectRows(Source, each Text.EndsWith([Folder Path], \"Commandes\\\")),",
                "    #\"Lignes filtrées1\" = Table.SelectRows(#\"Lignes filtrées\", each Text.StartsWith([Name], \"Commandes\")),",
                "    #\"Autres colonnes supprimées\" = Table.SelectColumns(#\"Lignes filtrées1\",{\"Name\"}),",
                "    #\"Fonction personnalisée appelée\" = Table.AddColumn(#\"Autres colonnes supprimées\", \"Modele_Commandes\", each Modele_Commandes([Name])),",
                "    #\"Modele_Commandes développé\" = Table.ExpandTableColumn(#\"Fonction personnalisée appelée\", \"Modele_Commandes\", {\"OrderID\", \"CustomerID\", \"EmployeeID\", \"OrderDate\", \"RequiredDate\", \"ShippedDate\", \"ShipVia\", \"Freight\", \"ShipCountry\"}, {\"OrderID\", \"CustomerID\", \"EmployeeID\", \"OrderDate\", \"RequiredDate\", \"ShippedDate\", \"ShipVia\", \"Freight\", \"ShipCountry\"}),",
                "    #\"Lignes filtrées2\" = Table.SelectRows(#\"Modele_Commandes développé\", each true),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"Lignes filtrées2\",{{\"OrderID\", Int64.Type}, {\"CustomerID\", type text}, {\"EmployeeID\", Int64.Type}, {\"OrderDate\", type datetime}, {\"RequiredDate\", type datetime}, {\"ShippedDate\", type datetime}, {\"ShipVia\", Int64.Type}, {\"Freight\", type number}, {\"ShipCountry\", type text}})",
                "in",
                "    #\"Type modifié\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Detail_Commande",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "OrderID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7d554a00-0e50-4f94-8192-5e40f6e7048d",
            "sourceColumn": "OrderID",
            "summarizeBy": "none"
          },
          {
            "name": "ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "634064de-2373-40c9-8642-2b031fb21f03",
            "sourceColumn": "ProductID",
            "summarizeBy": "none"
          },
          {
            "name": "UnitPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a0c5eb71-be20-4579-b4e7-fee6836d0999",
            "sourceColumn": "UnitPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "36ddb7ad-3101-4e19-83b8-e902c057c91d",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Discount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "ff280134-794e-459c-b81e-e575315c93c4",
            "sourceColumn": "Discount",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "2e9405e9-9a85-4e01-b997-9f4f8c055e52",
        "partitions": [
          {
            "name": "Detail_Commande-89d80e77-a267-4bed-9bc5-c5b56dc54296",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(Chemin_Dossier & \"Detail_Commandes.xlsx\"), null, true),",
                "    Detail_Commande_Sheet = Source{[Item=\"Detail_Commande\",Kind=\"Sheet\"]}[Data],",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(Detail_Commande_Sheet, [PromoteAllScalars=true]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"OrderID\", Int64.Type}, {\"ProductID\", Int64.Type}, {\"UnitPrice\", type number}, {\"Quantity\", Int64.Type}, {\"Discount\", type text}}),",
                "    #\"Type modifié avec paramètres régionaux\" = Table.TransformColumnTypes(#\"Type modifié\", {{\"Discount\", type number}}, \"en-US\"),",
                "    #\"Erreurs remplacées\" = Table.ReplaceErrorValues(#\"Type modifié avec paramètres régionaux\", {{\"Discount\", 0}})",
                "in",
                "    #\"Erreurs remplacées\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Categories",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "CategoryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3a814c15-1805-41af-88f7-a9cd4b500bc6",
            "sourceColumn": "CategoryID",
            "summarizeBy": "none"
          },
          {
            "name": "CategoryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a01c4c8b-135c-4c39-9b7e-c23054bcb01a",
            "sourceColumn": "CategoryName",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83b81517-0ece-40ce-9d3d-25fe627a120a",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "Picture",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "165a3c7c-c079-4af2-9dd2-d18182ab24e2",
            "sourceColumn": "Picture",
            "summarizeBy": "none"
          },
          {
            "name": "Regroupement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf856124-a4e7-4692-ad94-d5a0929807e2",
            "sourceColumn": "Regroupement",
            "summarizeBy": "none"
          },
          {
            "name": "Libelle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97ab0c54-a08d-47c8-8bf4-bbea734f39f1",
            "sourceColumn": "Libelle",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "33b8dbc4-55e6-4b7c-8cae-c6796605a154",
        "partitions": [
          {
            "name": "Categories-ce4a72f0-cc13-4dfb-8b8c-66a6e6e0a9d2",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents( Chemin_Dossier & \"Dimensions.xlsx\"), null, true),",
                "    Categories_Sheet = Source{[Item=\"Categories\",Kind=\"Sheet\"]}[Data],",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(Categories_Sheet, [PromoteAllScalars=true]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"CategoryID\", Int64.Type}, {\"CategoryName\", type text}, {\"Description\", type text}, {\"Picture\", type text}, {\"Regroupement\", type text}}),",
                "    #\"Personnalisée ajoutée\" = Table.AddColumn(#\"Type modifié\", \"Libelle\", each \"☱ \"&[CategoryName]),",
                "    #\"Type modifié1\" = Table.TransformColumnTypes(#\"Personnalisée ajoutée\",{{\"Libelle\", type text}})",
                "in",
                "    #\"Type modifié1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Clients",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f540432e-d47b-49f4-8aa0-bb3b44ba56fd",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none"
          },
          {
            "name": "CompanyName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac5abb5e-33ab-482f-98a9-2e104e992fb0",
            "sourceColumn": "CompanyName",
            "summarizeBy": "none"
          },
          {
            "name": "ContactName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e8e2162-8cfd-4464-aed1-969097af8dcb",
            "sourceColumn": "ContactName",
            "summarizeBy": "none"
          },
          {
            "name": "ContactTitle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "72b74f41-e1bc-41e3-a026-30a30f05e0ba",
            "sourceColumn": "ContactTitle",
            "summarizeBy": "none"
          },
          {
            "name": "Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f173efe-98bf-4fe5-92a8-6312ba907196",
            "sourceColumn": "Address",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c6264d8-292e-4202-a139-0e4f15a30bb5",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b7d0d777-95bc-4b33-86dd-82cc638dd588",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "PostalCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d8bb86b8-2106-46d2-9028-687966133038",
            "sourceColumn": "PostalCode",
            "summarizeBy": "count"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35ba1e0a-0861-4905-9113-c86d9a132150",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Phone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5833558b-7b36-4519-a43a-0b40c7299f33",
            "sourceColumn": "Phone",
            "summarizeBy": "none"
          },
          {
            "name": "Fax",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c26eb49b-cad0-4a1f-93b8-e4a12a07817d",
            "sourceColumn": "Fax",
            "summarizeBy": "none"
          },
          {
            "name": "Regroupement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f356422-2a0f-4012-993e-d79102868b72",
            "sourceColumn": "Regroupement",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a9c74f39-99c5-4f14-ae1c-2dcfc32ecbb7",
        "partitions": [
          {
            "name": "Clients-16d41c41-1c65-49b9-8f0d-e8133cfd3b73",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(Chemin_Dossier & \"Dimensions.xlsx\"), null, true),",
                "    Clients_Sheet = Source{[Item=\"Clients\",Kind=\"Sheet\"]}[Data],",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(Clients_Sheet, [PromoteAllScalars=true]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"CustomerID\", type text}, {\"CompanyName\", type text}, {\"ContactName\", type text}, {\"ContactTitle\", type text}, {\"Address\", type text}, {\"City\", type text}, {\"Region\", Int64.Type}, {\"PostalCode\", Int64.Type}, {\"Country\", type text}, {\"Phone\", type any}, {\"Fax\", type any}, {\"Regroupement\", type text}}),",
                "    #\"Lignes filtrées\" = Table.SelectRows(#\"Type modifié\", each [CompanyName] <> null and [CompanyName] <> \"\")",
                "in",
                "    #\"Lignes filtrées\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Employes",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "EmployeeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c5c50a97-9c81-48ff-8ab7-05f502cca700",
            "sourceColumn": "EmployeeID",
            "summarizeBy": "none"
          },
          {
            "name": "LastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a70dfd71-1e03-4dec-906f-c990d695cb17",
            "sourceColumn": "LastName",
            "summarizeBy": "none"
          },
          {
            "name": "FirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b2f0c7c-f178-44f1-b025-03d2bcf488e9",
            "sourceColumn": "FirstName",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dbc1ca1c-149d-4a7b-9ce3-e56bb5f51e63",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          },
          {
            "name": "TitleOfCourtesy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "10e038a0-ffed-4db8-9bfa-63382cfc91d5",
            "sourceColumn": "TitleOfCourtesy",
            "summarizeBy": "none"
          },
          {
            "name": "First_Last",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a078713a-17b1-46ee-b557-fc746670e6d5",
            "sourceColumn": "First_Last",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e4e4ecbd-6f83-4434-9104-fb2e95353db2",
        "partitions": [
          {
            "name": "Employes-a8468517-090b-486f-8ea0-9e6ecd5b5345",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(Chemin_Dossier & \"Dimensions.xlsx\"), null, true),",
                "    Employes_Sheet = Source{[Item=\"Employes\",Kind=\"Sheet\"]}[Data],",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(Employes_Sheet, [PromoteAllScalars=true]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"EmployeeID\", Int64.Type}, {\"LastName\", type text}, {\"FirstName\", type text}, {\"Title\", type text}, {\"TitleOfCourtesy\", type text}}),",
                "    #\"Personnalisée ajoutée\" = Table.AddColumn(#\"Type modifié\", \"First_Last\", each \"☲ \"&[FirstName]&\" \"&[LastName]),",
                "    #\"Type modifié1\" = Table.TransformColumnTypes(#\"Personnalisée ajoutée\",{{\"First_Last\", type text}}),",
                "    #\"Lignes filtrées\" = Table.SelectRows(#\"Type modifié1\", each ([EmployeeID] <> null))",
                "in",
                "    #\"Lignes filtrées\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Fournisseurs",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "SupplierID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8a87b023-0d69-4de6-be18-a010b06750e3",
            "sourceColumn": "SupplierID",
            "summarizeBy": "none"
          },
          {
            "name": "CompanyName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98efd13a-6fd0-4972-9528-bb2e0a460266",
            "sourceColumn": "CompanyName",
            "summarizeBy": "none"
          },
          {
            "name": "ContactName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f86504e9-5ba3-4ded-902c-61506292f8ef",
            "sourceColumn": "ContactName",
            "summarizeBy": "none"
          },
          {
            "name": "ContactTitle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a09e8b3-a3e7-4b86-ac9d-386b55d668f6",
            "sourceColumn": "ContactTitle",
            "summarizeBy": "none"
          },
          {
            "name": "Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a31f400f-1f2e-42b4-a542-84a30d8fcad3",
            "sourceColumn": "Address",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a3831de-54d9-43fc-9b20-24a71bc9a327",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e16e794-2a55-4e36-86f3-6b2324cde0d6",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "PostalCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "13e3c858-43e1-4338-b65c-7b01eabf3db7",
            "sourceColumn": "PostalCode",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8057609a-9558-4a85-a990-5eaba4a4214d",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Phone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5d013444-6cd2-4de6-b8ca-ad8d5d2b4a66",
            "sourceColumn": "Phone",
            "summarizeBy": "none"
          },
          {
            "name": "Fax",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "03c6c47e-5bfe-4296-affa-8a6ebc240ef5",
            "sourceColumn": "Fax",
            "summarizeBy": "none"
          },
          {
            "name": "HomePage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b37e3122-2167-45c8-8e18-3b4ba4e768c7",
            "sourceColumn": "HomePage",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "56f1081a-e84b-4d43-a6b0-33ca902b6ff1",
        "partitions": [
          {
            "name": "Fournisseurs-bd715322-1632-4b7e-bdc6-4205dff645f0",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(Chemin_Dossier & \"Dimensions.xlsx\"), null, true),",
                "    Fournisseurs_Sheet = Source{[Item=\"Fournisseurs\",Kind=\"Sheet\"]}[Data],",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(Fournisseurs_Sheet, [PromoteAllScalars=true]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"SupplierID\", Int64.Type}, {\"CompanyName\", type text}, {\"ContactName\", type text}, {\"ContactTitle\", type text}, {\"Address\", type text}, {\"City\", type text}, {\"Region\", type text}, {\"PostalCode\", type any}, {\"Country\", type text}, {\"Phone\", type any}, {\"Fax\", type any}, {\"HomePage\", type any}})",
                "in",
                "    #\"Type modifié\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Produits",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2cc1bd9d-6f2f-4da8-a720-db3edb95638f",
            "sourceColumn": "ProductID",
            "summarizeBy": "none"
          },
          {
            "name": "ProductName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6588316e-0cbc-480d-9490-fd69bc3cc97b",
            "sourceColumn": "ProductName",
            "summarizeBy": "none"
          },
          {
            "name": "SupplierID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dad05ee1-71ea-49fd-b749-aa96a9db0fe6",
            "sourceColumn": "SupplierID",
            "summarizeBy": "none"
          },
          {
            "name": "CategoryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "60c05821-4283-4f08-9149-a8e2eaf3480f",
            "sourceColumn": "CategoryID",
            "summarizeBy": "none"
          },
          {
            "name": "QuantityPerUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ae9a942-3435-4f48-a84a-507e60f7a993",
            "sourceColumn": "QuantityPerUnit",
            "summarizeBy": "none"
          },
          {
            "name": "UnitPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b439d911-cef5-4790-9f8d-4a3acb1c8c24",
            "sourceColumn": "UnitPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "Fichier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae850805-311e-4580-9529-2d78ed031ed7",
            "sourceColumn": "Fichier",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "40c13df1-03cc-4746-b336-fb2bf9acd93b",
        "partitions": [
          {
            "name": "Produits-5f734329-d36e-4f73-8e00-d197efbfef79",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(Chemin_Dossier & \"Dimensions.xlsx\"), null, true),",
                "    Produits_Sheet = Source{[Item=\"Produits\",Kind=\"Sheet\"]}[Data],",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(Produits_Sheet, [PromoteAllScalars=true]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"ProductID\", Int64.Type}, {\"ProductName\", type text}, {\"SupplierID\", Int64.Type}, {\"CategoryID\", Int64.Type}, {\"QuantityPerUnit\", type text}, {\"UnitPrice\", type number}, {\"Fichier\", type any}})",
                "in",
                "    #\"Type modifié\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Region",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Code_region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6e9d25e2-bc6c-40aa-81fc-e5796b1d7b06",
            "sourceColumn": "Code_region",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f229767b-abdc-4048-a813-04339592cb0b",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Libelle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf38a59f-a7f8-4131-ae58-6975140d766c",
            "sourceColumn": "Libelle",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "26e40587-dee7-4dc2-92c3-3b2fa893a9d5",
        "partitions": [
          {
            "name": "Region-1145df3a-a98f-4fe1-91ac-282392d2b00c",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(Chemin_Dossier & \"Dimensions.xlsx\"), null, true),",
                "    Region_Sheet = Source{[Item=\"Region\",Kind=\"Sheet\"]}[Data],",
                "    #\"En-têtes promus\" = Table.PromoteHeaders(Region_Sheet, [PromoteAllScalars=true]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"En-têtes promus\",{{\"Code_region\", Int64.Type}, {\"Region\", type text}}),",
                "    #\"Lignes filtrées\" = Table.SelectRows(#\"Type modifié\", each ([Region] <> \"NA\" and [Region] <> \"Test\")),",
                "    #\"Valeur remplacée\" = Table.ReplaceValue(#\"Lignes filtrées\",\"Provence-Alpes-Côte d'Azur\",\"PACA\",Replacer.ReplaceText,{\"Region\"}),",
                "    #\"Valeur remplacée1\" = Table.ReplaceValue(#\"Valeur remplacée\",\"Bourgogne-Franche-Comté\",\"Bourgogne-F-C\",Replacer.ReplaceText,{\"Region\"}),",
                "    #\"Personnalisée ajoutée\" = Table.AddColumn(#\"Valeur remplacée1\", \"Libelle\", each \"☴ \"&[Region]),",
                "    #\"Type modifié1\" = Table.TransformColumnTypes(#\"Personnalisée ajoutée\",{{\"Libelle\", type text}})",
                "in",
                "    #\"Type modifié1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Dim_Date",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isKey": true,
            "lineageTag": "57c59770-7007-4750-beb5-8ddcd5e6ca9d",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "59fca408-568c-469b-8149-bd93c3bdccfe",
            "sourceColumn": "Mois",
            "summarizeBy": "none"
          },
          {
            "name": "Nom du mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad58e1be-228e-41e8-85d4-4b323df2c481",
            "sortByColumn": "Mois",
            "sourceColumn": "Nom du mois",
            "summarizeBy": "none"
          },
          {
            "name": "Annee",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "21596495-2e4b-475c-b174-4055c35707c3",
            "sourceColumn": "Annee",
            "summarizeBy": "none"
          },
          {
            "name": "Mois_court",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "787b392b-356b-4a6a-938d-538b838b8f33",
            "sortByColumn": "Mois",
            "sourceColumn": "Mois_court",
            "summarizeBy": "none"
          },
          {
            "name": "Num_Jour_mois",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "89a49f6a-a59c-4e6e-9463-2312c1c8fb23",
            "sourceColumn": "Num_Jour_mois",
            "summarizeBy": "none"
          },
          {
            "name": "Periode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0caa2109-965a-45be-b3a6-43794c81742e",
            "sourceColumn": "Periode",
            "summarizeBy": "none"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "78459962-c261-418f-b52c-ac98ccbc8547",
            "sourceColumn": "Trimestre",
            "summarizeBy": "none"
          },
          {
            "name": "Exercice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "717ba068-a225-43d3-8d47-61dc6434ea4e",
            "sourceColumn": "Exercice",
            "summarizeBy": "none"
          },
          {
            "name": "Mois_annee",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(_Dim_Date[Date],\"yyyy-mm\")",
            "isDataTypeInferred": true,
            "lineageTag": "44347505-4331-4383-97ee-d661fb41c833",
            "sortByColumn": "Mois",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "dataCategory": "Time",
        "lineageTag": "9b88e928-129c-4464-acf1-c6ee17d4032f",
        "partitions": [
          {
            "name": "_Dim_Date-52530db9-48ba-43a0-8b4d-b48e8814fc42",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Date_debut = #date(2017,1,1),",
                "    Fin_annee = Date.EndOfYear (DateTime.Date (DateTime.LocalNow() )),",
                "    Premiere_date =List.Min(Liste_dates),",
                "    Derniere_date = List.Max(Liste_dates),",
                "",
                "    Duree =  Duration.Days(Fin_annee - Date_debut)+365,",
                "    Source = List.Dates( Date_debut, Duree, #duration(1,0,0,0)),",
                "    #\"Converti en table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    Colonne_date = Table.RenameColumns(#\"Converti en table\",{{\"Column1\", \"Date\"}}),",
                "    Change_type_date = Table.TransformColumnTypes(Colonne_date,{{\"Date\", type date}}),",
                "    Ajout_num_mois = Table.AddColumn(Change_type_date, \"Mois\", each Date.Month([Date]), Int64.Type),",
                "    Ajout_mois_long = Table.AddColumn(Ajout_num_mois, \"Nom du mois\", each Date.MonthName([Date]), type text),",
                "    Ajout_annee = Table.AddColumn(Ajout_mois_long, \"Annee\", each Date.Year([Date]), Int64.Type ),",
                "    Ajout_mois_court = Table.AddColumn(Ajout_annee, \"Mois_court\", each Text.Start ([Nom du mois],4), type text),",
                "    Ajout_num_jour_mois = Table.AddColumn(Ajout_mois_court, \"Num_Jour_mois\", each Date.Day([Date]), Int64.Type),",
                "    Ajout_Periode = Table.AddColumn(Ajout_num_jour_mois, \"Periode\", each if [Mois] >= 9 then [Mois]-8 else [Mois]+4,Int64.Type),",
                "    Ajout_Trimestre = Table.AddColumn(Ajout_Periode, \"Trimestre\", each \"Trimestre \" & Text.From(Number.RoundUp([Periode]/3)),type text),",
                "    Ajout_Exercice = Table.AddColumn(Ajout_Trimestre, \"Exercice\", each if [Mois] >=9 then \"Exercice \" & Text.From([Annee]) & \"-\" & Text.From([Annee]+1) else \"Exercice \" & Text.From([Annee]-1) & \"-\" & Text.From([Annee]), type text)",
                "in",
                "    Ajout_Exercice"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Mesures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "6848afa0-df2f-4caf-8ee6-8e63b2633e48",
        "measures": [
          {
            "name": "Qte",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Nbre",
            "expression": "SUM(Detail_Commande[Quantity])",
            "formatString": "#,0",
            "lineageTag": "5a0f5420-5657-428b-bd63-f7f2112085c9"
          },
          {
            "name": "CA",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "CA",
            "expression": "SUMX(Detail_Commande,[UnitPrice]*[Quantity])",
            "formatString": "#,0\\ \"€\";-#,0\\ \"€\";#,0\\ \"€\"",
            "lineageTag": "fd94a78a-0b89-467a-8331-d09ce286a4a8"
          },
          {
            "name": "CA_N-1",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "CA",
            "expression": [
              "CALCULATE(",
              "                    [CA]",
              "                    ,SAMEPERIODLASTYEAR(_Dim_Date[Date])",
              "                    )"
            ],
            "formatString": "#,0\\ \"€\";-#,0\\ \"€\";#,0\\ \"€\"",
            "lineageTag": "812f0fd3-a79e-4d8e-86c4-c339295e0844"
          },
          {
            "name": "CA_N-2",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "CA",
            "expression": [
              "CALCULATE(",
              "                    [CA]",
              "                    , DATEADD(_Dim_Date[Date],-2,YEAR)",
              "                    )"
            ],
            "formatString": "#,0\\ \"€\";-#,0\\ \"€\";#,0\\ \"€\"",
            "lineageTag": "a5c1e400-c983-4fba-bf30-239b213e9605"
          },
          {
            "name": "CA_X",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "CA",
            "expression": [
              "CALCULATE(",
              "                    [CA]",
              "                    ,DATEADD(_Dim_Date[Date],-'Choix Année'[Valeur Choix Année],YEAR)",
              "                    )"
            ],
            "formatString": "#,0\\ \"€\";-#,0\\ \"€\";#,0\\ \"€\"",
            "lineageTag": "c1d5ed41-6cd1-4663-905d-3b5b772a00ec"
          },
          {
            "name": "CA_Employe_2019",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "CA",
            "expression": [
              "CALCULATE(",
              "                                                  [CA]",
              "                            ,Employes[LastName] = \"King\"",
              "                            ,_Dim_Date[Annee]=2019",
              "                                    )",
              "                           "
            ],
            "lineageTag": "8efe9ed6-cbc6-41b0-a195-3273d8a9b61a"
          },
          {
            "name": "Ecart_CA_N-1",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "CA",
            "expression": "[CA]-[CA_N-1]",
            "formatString": "#,0\\ \"€\";-#,0\\ \"€\";#,0\\ \"€\"",
            "lineageTag": "68587622-dc1c-4de8-9da4-c7f83a774be9"
          },
          {
            "name": "%_Evol_CA_N-1",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "CA",
            "expression": [
              "DIVIDE([Ecart_CA_N-1]",
              "                        ,[CA_N-1]",
              "                        ,BLANK()",
              "                        )"
            ],
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "f4e34c15-b5c6-4a2c-93b5-8dbead79ee58"
          },
          {
            "name": "Nbre_commandes",
            "displayFolder": "Nbre",
            "expression": "DISTINCTCOUNT(Commandes[OrderID])",
            "formatString": "0",
            "lineageTag": "927c76dc-0cad-41de-ab02-4cb9653a0f05"
          },
          {
            "name": "Nbre_clients_cde",
            "displayFolder": "Nbre",
            "expression": [
              "CALCULATE(",
              "                                COUNTROWS(Clients)",
              "                                ,FILTER(Detail_Commande,[Quantity]>0))"
            ],
            "formatString": "0",
            "lineageTag": "81603b25-a7d2-4e11-bd31-db13bbac4657"
          },
          {
            "name": "Nbre_clients_Nocde",
            "displayFolder": "Nbre",
            "expression": [
              "CALCULATE(",
              "                                COUNTROWS(Clients)",
              "                                ,FILTER(Detail_Commande,[Quantity]=0))"
            ],
            "formatString": "0",
            "lineageTag": "1fc8d7c6-ddee-4b5b-9159-abaacf335bb1"
          },
          {
            "name": "CA_Cumule",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "CA",
            "expression": "CALCULATE([CA],DATESYTD(_Dim_Date[Date]))",
            "formatString": "#,0\\ \"€\";-#,0\\ \"€\";#,0\\ \"€\"",
            "lineageTag": "8dd21898-72ea-402f-98d5-3a014516091c"
          },
          {
            "name": "CA_ALL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "CA",
            "expression": "CALCULATE([CA],ALL(_Dim_Date[Date]))",
            "lineageTag": "c434a363-732b-4c2b-94ab-d3eb3b814773"
          },
          {
            "name": "Titre",
            "displayFolder": "Visuels & titres",
            "expression": [
              "",
              "            \"Analyse du CA du \" ",
              "            & FORMAT(MIN(_Dim_Date[Date]),\"dddd dd mmmm yyyy\") ",
              "            & \" au \" ",
              "            & MAX(_Dim_Date[Date])",
              "            & \" en \" ",
              "            & SELECTEDVALUE(Region[Region])"
            ],
            "lineageTag": "6eb77516-1282-452f-8f8b-70e93341e02a"
          },
          {
            "name": "Couleur_CA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "MEFC",
            "expression": [
              "",
              "IF( SELECTEDVALUE(Temps[Temps]) in {\"Delta\",\"Evol\"},[CA],BLANK())",
              "",
              ""
            ],
            "lineageTag": "f3578b84-0446-46ee-b001-a5c2b1347f1f"
          },
          {
            "name": "CA_conditional_format",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "CA",
            "expression": "[CA]",
            "lineageTag": "b571a275-a029-49d5-82df-1782dc6a376b"
          },
          {
            "name": "Tableau_HTML",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "HTML",
            "expression": [
              "",
              "",
              "",
              "/* Mettre en table virtuelle les mesures par catégories en embarquant les mises en forme conditionnelles et les choix de tri*/",
              "VAR _SourceData =",
              "",
              "/* Création de 3 tables par UNION (Catégories + Clients + Régions )*/",
              "UNION(",
              "",
              "/* Création de la table CATEGORIES : */",
              "",
              "WINDOW(0,ABS,100,REL,    /* Le fenetrage permet l'adjonction du ORDER BY pour le tri */",
              "        ",
              "                SUMMARIZE( Categories,",
              "                    Categories[Libelle]",
              "                    ,\"Actual_Qte\", FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"Actual\" ), \"#,##0\" )",
              "                    ,\"Actual_CA\", FORMAT( CALCULATE ( [CA], Temps[Temps] = \"Actual\" ), \"#,##0 €\" )",
              "                    ,\"N-1_Qte\", FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"N-1\" ), \"#,##0\" )",
              "                    ,\"N-1_CA\", FORMAT( CALCULATE ( [CA], Temps[Temps] = \"N-1\" ), \"#,##0 €\" )",
              "",
              "                    /* Blocs mise en forme conditionnelle */",
              "",
              "                    ,\"Delta_Qte\", IF(",
              "                                CALCULATE ( [Qte], Temps[Temps] = \"Delta\" )>=0",
              "                                ,\"<span style='color:#678B18;font-weight:bold;font-size:23px;'</span>\"& FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"Delta\" ), \"#,##0\" )",
              "                                , \"<span id=\"\"negatif1\"\" style='color:#C42222;'</span>\"& FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"Delta\" ), \"#,##0\" ) ",
              "                                    )",
              "                    ,\"Delta_CA\", IF(",
              "                                CALCULATE ( [CA], Temps[Temps] = \"Delta\" )>=0",
              "                                ,\"<span style='color:#678B18;font-weight:bold;font-size:23px;'</span>\"& FORMAT( CALCULATE ( [CA], Temps[Temps] = \"Delta\" ), \"#,##0 €\" )",
              "                                , \"<span id=\"\"negatif1\"\" style='color:#C42222;'</span>\"& FORMAT( CALCULATE ( [CA], Temps[Temps] = \"Delta\" ), \"#,##0 €\" ) ",
              "                                    )",
              "                    ,\"Evol_Qte\", IF(",
              "                                CALCULATE ( [Qte], Temps[Temps] = \"Evol\" )>=0",
              "                                ,\"<span style='color:#678B18;font-weight:bold;font-size:23px;'</span>\"& FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"Evol\" ), \"#0.0 %\" )",
              "                                , \"<span id=\"\"negatif1\"\" style='color:#C42222;'</span>\"& FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"Evol\" ), \"#0.0 %\" ) ",
              "                                    )",
              "                    ,\"Evol_CA\", IF(",
              "                                CALCULATE ( [CA], Temps[Temps] = \"Evol\" )>=0",
              "                                ,\"<span style='color:#678B18;font-weight:bold;font-size:23px;'</span>\"& FORMAT( CALCULATE ( [CA], Temps[Temps] = \"Evol\" ), \"#0.0 %\" )",
              "                                , \"<span id=\"\"negatif1\"\" style='color:#C42222;'</span>\"& FORMAT( CALCULATE ( [CA], Temps[Temps] = \"Evol\" ), \"#0.0 %\" ) ",
              "                                    )",
              "                            )",
              "",
              "                /* Blocs de tri */",
              "",
              "                ,ORDERBY(",
              "                            SWITCH(",
              "                                SELECTEDVALUE(Choix_HTML_Rank[Tri])",
              "                                ,1,CALCULATE ( [Qte], Temps[Temps] = \"Actual\" )",
              "                                ,2,CALCULATE ( [CA], Temps[Temps] = \"Actual\" )",
              "                                ,3,CALCULATE ( [Qte], Temps[Temps] = \"N-1\" )",
              "                                ,4,CALCULATE ( [CA], Temps[Temps] = \"N-1\" )",
              "                                ,5,CALCULATE ( [Qte], Temps[Temps] = \"Delta\" )",
              "                                ,6,CALCULATE ( [CA], Temps[Temps] = \"Delta\" )",
              "                                ,7,CALCULATE ( [Qte], Temps[Temps] = \"Evol\" )",
              "                                ,8,CALCULATE ( [CA], Temps[Temps] = \"Evol\" )",
              "                                    )",
              "                        ,DESC)",
              "            )",
              "",
              "/* Création de la table REGION : */",
              ",WINDOW(0,ABS,100,REL,    /* Le fenetrage permet l'adjonction du ORDER BY pour le tri */",
              "    ",
              "                SUMMARIZE( Region,",
              "                    Region[Libelle]",
              "                    ,\"Actual_Qte\", FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"Actual\" ), \"#,##0\" )",
              "                    ,\"Actual_CA\", FORMAT( CALCULATE ( [CA], Temps[Temps] = \"Actual\" ), \"#,##0 €\" )",
              "                    ,\"N-1_Qte\", FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"N-1\" ), \"#,##0\" )",
              "                    ,\"N-1_CA\", FORMAT( CALCULATE ( [CA], Temps[Temps] = \"N-1\" ), \"#,##0 €\" )",
              "",
              "                    /* Blocs mise en forme conditionnelle */",
              "",
              "                    ,\"Delta_Qte\", IF(",
              "                                CALCULATE ( [Qte], Temps[Temps] = \"Delta\" )>=0",
              "                                ,\"<span style='color:#678B18;font-weight:bold;font-size:23px;'</span>\"& FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"Delta\" ), \"#,##0\" )",
              "                                , \"<span id=\"\"negatif1\"\" style='color:#C42222;'</span>\"& FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"Delta\" ), \"#,##0\" ) ",
              "                                    )",
              "                    ,\"Delta_CA\", IF(",
              "                                CALCULATE ( [CA], Temps[Temps] = \"Delta\" )>=0",
              "                                ,\"<span style='color:#678B18;font-weight:bold;font-size:23px;'</span>\"& FORMAT( CALCULATE ( [CA], Temps[Temps] = \"Delta\" ), \"#,##0 €\" )",
              "                                , \"<span id=\"\"negatif1\"\" style='color:#C42222;'</span>\"& FORMAT( CALCULATE ( [CA], Temps[Temps] = \"Delta\" ), \"#,##0 €\" ) ",
              "                                    )",
              "                    ,\"Evol_Qte\", IF(",
              "                                CALCULATE ( [Qte], Temps[Temps] = \"Evol\" )>=0",
              "                                ,\"<span style='color:#678B18;font-weight:bold;font-size:23px;'</span>\"& FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"Evol\" ), \"#0.0 %\" )",
              "                                , \"<span id=\"\"negatif1\"\" style='color:#C42222;'</span>\"& FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"Evol\" ), \"#0.0 %\" ) ",
              "                                    )",
              "                    ,\"Evol_CA\", IF(",
              "                                CALCULATE ( [CA], Temps[Temps] = \"Evol\" )>=0",
              "                                ,\"<span style='color:#678B18;font-weight:bold;font-size:23px;'</span>\"& FORMAT( CALCULATE ( [CA], Temps[Temps] = \"Evol\" ), \"#0.0 %\" )",
              "                                , \"<span id=\"\"negatif1\"\" style='color:#C42222;'</span>\"& FORMAT( CALCULATE ( [CA], Temps[Temps] = \"Evol\" ), \"#0.0 %\" ) ",
              "                                    )",
              "                            )",
              "",
              "                /* Blocs de tri */",
              "",
              "                ,ORDERBY(",
              "                            SWITCH(",
              "                                SELECTEDVALUE(Choix_HTML_Rank[Tri])",
              "                                ,1,CALCULATE ( [Qte], Temps[Temps] = \"Actual\" )",
              "                                ,2,CALCULATE ( [CA], Temps[Temps] = \"Actual\" )",
              "                                ,3,CALCULATE ( [Qte], Temps[Temps] = \"N-1\" )",
              "                                ,4,CALCULATE ( [CA], Temps[Temps] = \"N-1\" )",
              "                                ,5,CALCULATE ( [Qte], Temps[Temps] = \"Delta\" )",
              "                                ,6,CALCULATE ( [CA], Temps[Temps] = \"Delta\" )",
              "                                ,7,CALCULATE ( [Qte], Temps[Temps] = \"Evol\" )",
              "                                ,8,CALCULATE ( [CA], Temps[Temps] = \"Evol\" )",
              "                                    )",
              "                        ,DESC)",
              "            ) ",
              "",
              "/* Création de la table CLIENTS : */",
              ",WINDOW(0,ABS,100,REL,    /* Le fenetrage permet l'adjonction du ORDER BY pour le tri */",
              "     ",
              "                SUMMARIZE( Employes,",
              "                    Employes[First_Last]  /*Clients,Clients[CompanyName]*/",
              "                    ,\"Actual_Qte\", FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"Actual\" ), \"#,##0\" )",
              "                    ,\"Actual_CA\", FORMAT( CALCULATE ( [CA], Temps[Temps] = \"Actual\" ), \"#,##0 €\" )",
              "                    ,\"N-1_Qte\", FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"N-1\" ), \"#,##0\" )",
              "                    ,\"N-1_CA\", FORMAT( CALCULATE ( [CA], Temps[Temps] = \"N-1\" ), \"#,##0 €\" )",
              "",
              "                    /* Blocs mise en forme conditionnelle */",
              "",
              "                    ,\"Delta_Qte\", IF(",
              "                                CALCULATE ( [Qte], Temps[Temps] = \"Delta\" )>=0",
              "                                ,\"<span style='color:#678B18;font-weight:bold;font-size:23px;'</span>\"& FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"Delta\" ), \"#,##0\" )",
              "                                , \"<span id=\"\"negatif1\"\" style='color:#C42222;'</span>\"& FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"Delta\" ), \"#,##0\" ) ",
              "                                )",
              "                    ,\"Delta_CA\", IF(",
              "                                CALCULATE ( [CA], Temps[Temps] = \"Delta\" )>=0",
              "                                ,\"<span style='color:#678B18;font-weight:bold;font-size:23px;'</span>\"& FORMAT( CALCULATE ( [CA], Temps[Temps] = \"Delta\" ), \"#,##0 €\" )",
              "                                , \"<span id=\"\"negatif1\"\" style='color:#C42222;'</span>\"& FORMAT( CALCULATE ( [CA], Temps[Temps] = \"Delta\" ), \"#,##0 €\" ) ",
              "                                )",
              "                    ,\"Evol_Qte\", IF(",
              "                                CALCULATE ( [Qte], Temps[Temps] = \"Evol\" )>=0",
              "                                ,\"<span style='color:#678B18;font-weight:bold;font-size:23px;'</span>\"& FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"Evol\" ), \"#0.0 %\" )",
              "                                , \"<span id=\"\"negatif1\"\" style='color:#C42222;'</span>\"& FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"Evol\" ), \"#0.0 %\" ) ",
              "                                )",
              "                    ,\"Evol_CA\", IF(",
              "                                CALCULATE ( [CA], Temps[Temps] = \"Evol\" )>=0",
              "                                ,\"<span style='color:#678B18;font-weight:bold;font-size:23px;'</span>\"& FORMAT( CALCULATE ( [CA], Temps[Temps] = \"Evol\" ), \"#0.0 %\" )",
              "                                , \"<span id=\"\"negatif1\"\" style='color:#C42222;'</span>\"& FORMAT( CALCULATE ( [CA], Temps[Temps] = \"Evol\" ), \"#0.0 %\" ) ",
              "                                )",
              "                            )",
              "            ",
              "             /* Blocs de tri */",
              "",
              "                ,ORDERBY(",
              "                            SWITCH(",
              "                                SELECTEDVALUE(Choix_HTML_Rank[Tri])",
              "                                ,1,CALCULATE ( [Qte], Temps[Temps] = \"Actual\" )",
              "                                ,2,CALCULATE ( [CA], Temps[Temps] = \"Actual\" )",
              "                                ,3,CALCULATE ( [Qte], Temps[Temps] = \"N-1\" )",
              "                                ,4,CALCULATE ( [CA], Temps[Temps] = \"N-1\" )",
              "                                ,5,CALCULATE ( [Qte], Temps[Temps] = \"Delta\" )",
              "                                ,6,CALCULATE ( [CA], Temps[Temps] = \"Delta\" )",
              "                                ,7,CALCULATE ( [Qte], Temps[Temps] = \"Evol\" )",
              "                                ,8,CALCULATE ( [CA], Temps[Temps] = \"Evol\" )",
              "                                    )",
              "                        ,DESC)",
              "            ) ",
              "    )",
              "",
              "/* Creer un block HTML continu pour les valeurs de chaque ligne du tableau */",
              "VAR _TableRow =",
              "SWITCH(SELECTEDVALUE(Choix_CAT_CLT_REG[Choix_CAT_CLT_REG Commande])",
              "    ,0,CONCATENATEX(",
              "                    _SourceData,",
              "                    IF(LEFT([Libelle],1)=\"☱\",",
              "                    \"<tr>\"",
              "                        & \"<td class=\"\"colA\"\"><span id=\"\"marquee\"\">\" & [Libelle] & \"</span></td>\"",
              "                        & \"<td class=\"\"col1\"\">\" & [Actual_Qte] & \"</td>\"",
              "                        & \"<td class=\"\"col2\"\">\" & [Actual_CA] & \"</td>\"",
              "                        & \"<td class=\"\"col1\"\">\" & [N-1_Qte] & \"</td>\"",
              "                        & \"<td class=\"\"col2\"\">\" & [N-1_CA] & \"</td>\"",
              "                        & \"<td class=\"\"col1\"\">\" & [Delta_Qte] & \"</td>\"",
              "                        & \"<td class=\"\"col2\"\">\" & [Delta_CA] & \"</td>\"",
              "                        & \"<td class=\"\"col1\"\">\" & [Evol_Qte] & \"</td>\"",
              "                        & \"<td class=\"\"col2\"\">\" & [Evol_CA] & \"</td>\"",
              "                    & \"</tr>\"",
              "                    ,BLANK()",
              "                    ))",
              "    ,1,CONCATENATEX(",
              "                    _SourceData,",
              "                    IF(LEFT([Libelle],1)=\"☲\",",
              "                    \"<tr>\"",
              "                        & \"<td class=\"\"colA\"\"><span id=\"\"marquee\"\">\" & [Libelle] & \"</span></td>\"",
              "                        & \"<td class=\"\"col1\"\">\" & [Actual_Qte] & \"</td>\"",
              "                        & \"<td class=\"\"col2\"\">\" & [Actual_CA] & \"</td>\"",
              "                        & \"<td class=\"\"col1\"\">\" & [N-1_Qte] & \"</td>\"",
              "                        & \"<td class=\"\"col2\"\">\" & [N-1_CA] & \"</td>\"",
              "                        & \"<td class=\"\"col1\"\">\" & [Delta_Qte] & \"</td>\"",
              "                        & \"<td class=\"\"col2\"\">\" & [Delta_CA] & \"</td>\"",
              "                        & \"<td class=\"\"col1\"\">\" & [Evol_Qte] & \"</td>\"",
              "                        & \"<td class=\"\"col2\"\">\" & [Evol_CA] & \"</td>\"",
              "                    & \"</tr>\"",
              "                    ,BLANK()",
              "                    ))",
              "    ,2,CONCATENATEX(",
              "                    _SourceData,",
              "                    IF(LEFT([Libelle],1)=\"☴\",",
              "                    \"<tr>\"",
              "                        & \"<td class=\"\"colA\"\"><span id=\"\"marquee\"\">\" & [Libelle] & \"</span></td>\"",
              "                        & \"<td class=\"\"col1\"\">\" & [Actual_Qte] & \"</td>\"",
              "                        & \"<td class=\"\"col2\"\">\" & [Actual_CA] & \"</td>\"",
              "                        & \"<td class=\"\"col1\"\">\" & [N-1_Qte] & \"</td>\"",
              "                        & \"<td class=\"\"col2\"\">\" & [N-1_CA] & \"</td>\"",
              "                        & \"<td class=\"\"col1\"\">\" & [Delta_Qte] & \"</td>\"",
              "                        & \"<td class=\"\"col2\"\">\" & [Delta_CA] & \"</td>\"",
              "                        & \"<td class=\"\"col1\"\">\" & [Evol_Qte] & \"</td>\"",
              "                        & \"<td class=\"\"col2\"\">\" & [Evol_CA] & \"</td>\"",
              "                    & \"</tr>\"",
              "                    ,BLANK()",
              "                    ))",
              "            )",
              "/* Creer une ligne HTML simple pour le total du tableau */",
              "VAR _TotalRow =",
              "                    \"<tf>",
              "                        <td class = \"\"TotA\"\"> Total </td>",
              "                        <td class = \"\"Tot1\"\">\" & FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"Actual\" ), \"#,##0\" ) & \"</td>",
              "                        <td class = \"\"Tot2\"\">\" & FORMAT( CALCULATE ( [CA], Temps[Temps] = \"Actual\" ), \"#,##0 €\" ) & \"</td>",
              "                        <td class = \"\"Tot1\"\">\" & FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"N-1\" ), \"#,##0\" ) & \"</td>",
              "                        <td class = \"\"Tot2\"\">\" & FORMAT( CALCULATE ( [CA], Temps[Temps] = \"N-1\" ), \"#,##0 €\" ) & \"</td>",
              "                        <td class = \"\"Tot1\"\">\" & IF(",
              "                                                    CALCULATE ( [Qte], Temps[Temps] = \"Delta\" )>=0",
              "                                                    ,\"<span style='color:#678B18;font-weight:bold;'</span>\"& FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"Delta\" ), \"#,##0\" )",
              "                                                    , \"<span id=\"\"negatif1\"\" style='color:#C42222;'</span>\"& FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"Delta\" ), \"#,##0\" ) ",
              "                                                    ) & \"</td>",
              "                        <td class = \"\"Tot2\"\">\" & IF(",
              "                                                    CALCULATE ( [CA], Temps[Temps] = \"Delta\" )>=0",
              "                                                    ,\"<span style='color:#678B18;font-weight:bold;'</span>\"& FORMAT( CALCULATE ( [CA], Temps[Temps] = \"Delta\" ), \"#,##0 €\" )",
              "                                                    , \"<span id=\"\"negatif1\"\" style='color:#C42222;'</span>\"& FORMAT( CALCULATE ( [CA], Temps[Temps] = \"Delta\" ), \"#,##0 €\" ) ",
              "                                                    ) & \"</td>",
              "                        <td class = \"\"Tot1\"\">\" & IF(",
              "                                                    CALCULATE ( [Qte], Temps[Temps] = \"Evol\" )>=0",
              "                                                    ,\"<span style='color:#678B18;font-weight:bold;'</span>\"& FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"Evol\" ), \"#0.0 %\" )",
              "                                                    , \"<span id=\"\"negatif1\"\" style='color:#C42222;'</span>\"& FORMAT( CALCULATE ( [Qte], Temps[Temps] = \"Evol\" ), \"#0.0 %\" ) ",
              "                                                    ) & \"</td>",
              "                        <td class = \"\"Tot2\"\">\" & IF(",
              "                                                    CALCULATE ( [CA], Temps[Temps] = \"Evol\" )>=0",
              "                                                    ,\"<span style='color:#678B18;font-weight:bold;'</span>\"& FORMAT( CALCULATE ( [CA], Temps[Temps] = \"Evol\" ), \"#0.0 %\" )",
              "                                                    , \"<span id=\"\"negatif1\"\" style='color:#C42222;'</span>\"& FORMAT( CALCULATE ( [CA], Temps[Temps] = \"Evol\" ), \"#0.0 %\" ) ",
              "                                                    ) & \"</td>",
              "                        <td class = \"\"Tot3\"\">  </td>",
              "                    </tf>\"",
              "",
              "RETURN",
              "        \"<style>",
              "            #negatif1",
              "                {",
              "                animation: blinker 3s linear infinite;",
              "                font-size:23px;",
              "                font-weight:bold;",
              "                }",
              "                @keyframes blinker ",
              "                    {",
              "                    60% {opacity: 0;}",
              "                    }",
              "            #marquee",
              "                {",
              "                animation: 5s linear infinite slidein;",
              "                }",
              "                @keyframes slidein ",
              "                {",
              "                from { margin-left: 50%; }",
              "                to { margin-left: -50%; }",
              "                }",
              "            #TxTtourne ",
              "                {",
              "                animation-name: spin, depth;",
              "                animation-timing-function: linear;",
              "                animation-iteration-count: infinite;",
              "                animation-duration: 6s;",
              "                }",
              "                @keyframes ",
              "                spin {",
              "                    0% {",
              "                        transform: rotateY(0deg);",
              "                        }",
              "                    100% {",
              "                        transform: rotateY(-360deg);",
              "                        }",
              "                    }",
              "                @keyframes ",
              "                depth {",
              "                    0% {",
              "                        text-shadow: 0 0 black;",
              "                        }",
              "                    25% {",
              "                        text-shadow: 1px 0 black, 2px 0 black, 3px 0 black, 4px 0 black, 5px 0 black;",
              "                        }",
              "                    50% {",
              "                        text-shadow: 0 0 black;",
              "                        }",
              "                    75% {",
              "                        text-shadow: -1px 0 black, -2px 0 black, -3px 0 black, -4px 0 black,-5px 0 black;",
              "                        }",
              "                    100% {",
              "                        text-shadow: 0 0 black;",
              "                        }",
              "                    }",
              "            table{",
              "                border-collapse: collapse;",
              "                }",
              "            tfoot,tbody,thead",
              "                {",
              "                display: block;",
              "                }",
              "            tbody{",
              "                height : 276px;",
              "                overflow-y: scroll;",
              "                }",
              "            th {",
              "                height: 23px;",
              "                text-align: center;",
              "                vertical-align: middle;",
              "                font-face:Segoe UI;",
              "                font-weight:bold;",
              "                color:#678B18;",
              "                font-size:24px;",
              "                background-color:#DBF76E;",
              "                padding-left: 0px;",
              "                padding: 0px;",
              "                border-bottom: 1px solid grey;",
              "                border-color : #678B18;",
              "                }",
              "",
              "            tr {",
              "                height:23px",
              "                overflow: hidden;",
              "                white-space: nowrap;",
              "                text-overflow: ellipsis;",
              "                }",
              "",
              "            td",
              "                {",
              "                text-align: right;",
              "                vertical-align: middle;",
              "                font-face:Segoe UI;",
              "                font-size:23px;",
              "                color: black;",
              "                padding-right: 5px;",
              "                padding: 0px;",
              "                overflow: hidden;",
              "                white-space: nowrap;",
              "                text-overflow: ellipsis;",
              "                }",
              "",
              "            .headerA",
              "                {",
              "                width:291px;",
              "                overflow: hidden;",
              "                white-space: nowrap;",
              "                text-overflow: ellipsis;",
              "                vertical-align: left;",
              "                border-right: 1px solid grey;",
              "                }",
              "                ",
              "            .header1",
              "                {",
              "                width:80px;",
              "                overflow: hidden;",
              "                white-space: nowrap;",
              "                text-overflow: ellipsis;",
              "                border-right: 1px solid grey;",
              "                }",
              "",
              "            .headerX",
              "                {",
              "                width:80px;",
              "                overflow: hidden;",
              "                white-space: nowrap;",
              "                text-overflow: ellipsis;",
              "                border-right: 1px solid grey;",
              "                animation-name: spin, depth;",
              "                animation-timing-function: linear;",
              "                animation-iteration-count: infinite;",
              "                animation-duration: 6s;",
              "                }",
              "                @keyframes ",
              "                spin {",
              "                    0% {",
              "                        transform: rotateY(0deg);",
              "                        }",
              "                    100% {",
              "                        transform: rotateY(-360deg);",
              "                        }",
              "                    }",
              "                @keyframes ",
              "                depth {",
              "                    0% {",
              "                        text-shadow: 0 0 black;",
              "                        }",
              "                    25% {",
              "                        text-shadow: 1px 0 black, 2px 0 black, 3px 0 black, 4px 0 black, 5px 0 black;",
              "                        }",
              "                    50% {",
              "                        text-shadow: 0 0 black;",
              "                        }",
              "                    75% {",
              "                        text-shadow: -1px 0 black, -2px 0 black, -3px 0 black, -4px 0 black,-5px 0 black;",
              "                        }",
              "                    100% {",
              "                        text-shadow: 0 0 black;",
              "                        }",
              "                    }",
              "            .header2",
              "                {",
              "                width:150px;",
              "                overflow: hidden;",
              "                white-space: nowrap;",
              "                text-overflow: ellipsis;",
              "                border-right: 1px solid grey;",
              "                } ",
              "            .header3",
              "                {",
              "                width:20px;",
              "                } ",
              "            .colA",
              "                {",
              "                width:291px;",
              "                text-align: left;",
              "                padding-left: 5px;",
              "                border-right: 1px solid grey; ",
              "                border-color : #678B18;",
              "                overflow: hidden;",
              "                white-space: nowrap;",
              "                text-overflow: ellipsis;",
              "                }    ",
              "            .col1",
              "                {",
              "                width:80px;",
              "                padding-right: 5px;",
              "                overflow: hidden;",
              "                white-space: nowrap;",
              "                text-overflow: ellipsis;",
              "                border-right: 1px solid grey;",
              "                }",
              "            .col1:active {",
              "                height: 110px;",
              "                transform: rotate(45deg);",
              "                }",
              "            .col2",
              "                {",
              "                width:150px;",
              "                padding-right: 5px;",
              "                overflow: hidden;",
              "                white-space: nowrap;",
              "                text-overflow: ellipsis;",
              "                border-right: 1px solid grey;",
              "                }",
              "            .col2:hover {",
              "                height: 110px;",
              "                transform: rotate(45deg);",
              "                }",
              "            .TotA",
              "                {",
              "                width:291px;",
              "                padding-left: 5px;",
              "                text-align: left;",
              "                vertical-align: left;",
              "                font-face:Segoe UI;",
              "                font-weight:bold;",
              "                color:#678B18;",
              "                font-size:23px;",
              "                background-color:#DBF76E;",
              "                border-bottom: 1px #678B18;",
              "                border-right: 1px solid grey;",
              "                overflow: hidden;",
              "                white-space: nowrap;",
              "                text-overflow: ellipsis;",
              "                }    ",
              "            .Tot1",
              "                {",
              "                width:80px;",
              "                padding-right: 5px;",
              "                height: 20px;",
              "                text-align: right;",
              "                vertical-align: right;",
              "                font-face:Segoe UI;",
              "                font-weight:bold;",
              "                color:#678B18;",
              "                font-size:20px;",
              "                background-color:#DBF76E;",
              "                border-bottom: 1px #678B18;",
              "                overflow: hidden;",
              "                white-space: nowrap;",
              "                text-overflow: ellipsis;",
              "                }",
              "            .Tot2",
              "                {",
              "                width:150px;",
              "                padding-right: 5px;",
              "                height: 20px;",
              "                text-align: right;",
              "                vertical-align: right;",
              "                font-face:Segoe UI;",
              "                font-weight:bold;",
              "                color:#678B18;",
              "                font-size:20px;",
              "                background-color:#DBF76E;",
              "                border-bottom: 1px #678B18;",
              "                overflow: hidden;",
              "                white-space: nowrap;",
              "                text-overflow: ellipsis;",
              "                }",
              "            .Tot3",
              "                {",
              "                width:20px;",
              "                padding-right: 5px;",
              "                height: 20px;",
              "                text-align: right;",
              "                vertical-align: right;",
              "                font-face:Segoe UI;",
              "                font-weight:bold;",
              "                color:#678B18;",
              "                font-size:20px;",
              "                background-color:#DBF76E;",
              "                border-bottom: 1px #678B18;",
              "                overflow: hidden;",
              "                white-space: nowrap;",
              "                text-overflow: ellipsis;",
              "                }",
              "        </style>",
              "",
              "        <table>",
              "",
              "            <thead>",
              "                <tr>",
              "                    <th class = \"\"headerA\"\">   </th>",
              "                    <th class = \"\"headerX\"\" colspan=2 ><span id=\"\"TxTtourne\"\">\" & MAX(_Dim_Date[Annee]) & \"</span></th>  ",
              "                    <th class = \"\"headerX\"\" colspan=2 ><span id=\"\"TxTtourne\"\">\" & MAX(_Dim_Date[Annee])-1 & \"</span></th>",
              "                    <th class = \"\"header1\"\" colspan=2 ><span id=\"\"TxTtourne\"\"> Delta </span></th>",
              "                    <th class = \"\"header1\"\" colspan=2 ><span id=\"\"TxTtourne\"\"> Evol </span></th>",
              "                    <th class = \"\"header3\"\">  </th>",
              "                </tr>",
              "                <tr>",
              "                    <th class = \"\"headerA\"\"> Cat. / Rég. / Empl. </th>",
              "                    <th class = \"\"header1\"\"> Qte </th>",
              "                    <th class = \"\"header2\"\"> CA </th>",
              "                    <th class = \"\"header1\"\"> Qte </th>",
              "                    <th class = \"\"header2\"\"> CA </th>",
              "                    <th class = \"\"header1\"\"> Qte </th>",
              "                    <th class = \"\"header2\"\"> CA </th>",
              "                    <th class = \"\"header1\"\"> Qte </th>",
              "                    <th class = \"\"header2\"\"> CA </th>",
              "                    <th class = \"\"header3\"\">  </th>",
              "                </tr>",
              "            </thead>",
              "",
              "            <tbody>",
              "                \"& _TableRow &\"",
              "            </tbody>",
              "",
              "            <tfoot>",
              "                \"& _TotalRow &\"",
              "            </tfoot>",
              "",
              "        </table>\"",
              "",
              ""
            ],
            "lineageTag": "852efe86-0e0e-4220-970b-10d344e6038b"
          },
          {
            "name": "Qte_Cumule",
            "displayFolder": "Nbre",
            "expression": "CALCULATE([Qte],DATESYTD(_Dim_Date[Date]))",
            "formatString": "#,0",
            "lineageTag": "f66f3549-c091-4b7f-8ce8-4c776e68735f"
          },
          {
            "name": "Couleur_Qte",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "MEFC",
            "expression": [
              "",
              "IF( SELECTEDVALUE(Temps[Temps]) in {\"Delta\",\"Evol\"},[Qte],BLANK())"
            ],
            "lineageTag": "4c1d494a-aff5-47cf-b59f-37366a3f138f"
          },
          {
            "name": "Choix_couleur_Categories",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Visuels & titres",
            "expression": [
              "",
              "VAR _CAT = LOOKUPVALUE(Table_couleurs[CAT],Table_couleurs[CAT],SELECTEDVALUE(Categories[CategoryName]),\"N/C\")",
              "VAR _tableCouleurs = FILTER(Table_couleurs,[CAT]=_CAT)",
              "RETURN",
              "                MAXX(",
              "                    _tableCouleurs,",
              "                    [code_couleur]",
              "                    )"
            ],
            "lineageTag": "bbab7e6a-ab8a-4a96-afd6-7bae341b7e46"
          },
          {
            "name": "Format_CA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "CA",
            "expression": "FORMAT([CA],\"0,.0 K€\")",
            "lineageTag": "adb1d376-e088-4324-9e7d-ae2074790eb8"
          },
          {
            "name": "CA_ALL_CAT",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "CA",
            "expression": "CALCULATE([CA],REMOVEFILTERS(Categories[CategoryName]))",
            "lineageTag": "77b56c9f-0eea-4240-bb87-7cdb3bdc341f"
          },
          {
            "name": "CA2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "CA",
            "expression": "CALCULATE([CA],Temps[Temps]in{\"Actual\",\"N-1\",\"Delta\",\"Evol\"})",
            "lineageTag": "93c25546-c4a9-4e6d-9502-119ea4d6e729"
          },
          {
            "name": "QTE2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Nbre",
            "expression": "CALCULATE([Qte],REMOVEFILTERS(Temps_Tri))",
            "lineageTag": "33cb9cdc-a55e-43e1-b88d-7a56cb732d5b"
          },
          {
            "name": "Qte_N-1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "Nbre",
            "expression": [
              "CALCULATE(",
              "                    [Qte]",
              "                    ,SAMEPERIODLASTYEAR(_Dim_Date[Date])",
              "                    )"
            ],
            "formatString": "#,0",
            "lineageTag": "07e686c4-87c4-40f0-8d36-8504a6044f3f"
          },
          {
            "name": "Delta_Qte_N-1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "CA",
            "expression": "[Qte]-[Qte_N-1]",
            "formatString": "#,0",
            "lineageTag": "c904ba66-19c8-4278-8333-332fa8056ddd"
          },
          {
            "name": "Delta_CA",
            "displayFolder": "CA",
            "expression": "[CA]-[CA_N-1]",
            "formatString": "#,0\\ \"€\";-#,0\\ \"€\";#,0\\ \"€\"",
            "lineageTag": "e86b6d34-eff7-499d-aff4-13efa8cf0f8c"
          },
          {
            "name": "Evol_Qte",
            "displayFolder": "CA",
            "expression": [
              "DIVIDE(",
              "                    [Delta_Qte_N-1]",
              "                    ,[Qte_N-1]",
              "                    ,BLANK()",
              "                    )"
            ],
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "204943a9-fc18-460e-8507-dfbfbdfdb8e6"
          },
          {
            "name": "Evol_CA",
            "displayFolder": "CA",
            "expression": [
              "DIVIDE(",
              "                    [Delta_CA]",
              "                    ,[CA_N-1]",
              "                    ,BLANK()",
              "                    )"
            ],
            "formatString": "0.0\\ %;-0.0\\ %;0.0\\ %",
            "lineageTag": "4fb4c161-c11f-4328-ae9a-d5f6e7a385c2"
          },
          {
            "name": "Rotateonaxis_logo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "HTML",
            "expression": [
              "",
              "VAR _Image1 = \"https://i.ibb.co/kxQQsXL/t-l-chargement-jpeg.jpg\"",
              "RETURN",
              "\"",
              "<style>",
              "<!--",
              "    #imgtourne ",
              "            {",
              "            border-radius: 0px;",
              "            margin-top:0px;",
              "            margin-bottom:0px;",
              "            margin-left: 0px;",
              "            -webkit-animation: rotateAnim 10s linear infinite;",
              "            }",
              "    @keyframes rotateAnim {",
              "                        from {-webkit-transform: rotateY(0);}",
              "                        to {-webkit-transform: rotateY(360deg);}",
              "                            }",
              "-->",
              "</style>",
              "    <img id=\"\"imgtourne\"\" src=\" & _Image1 & \" style='width:85px;height:76px;' alt=\"\"tourne\"\" />",
              "\""
            ],
            "lineageTag": "426a56e7-2124-43c4-bb42-e5a94a3bdec8"
          },
          {
            "name": "Titre_dynamique",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Visuels & titres",
            "expression": "\"Analyses de la catégorie \"&SELECTEDVALUE(Categories[CategoryName])&\" sur l'année \"&SELECTEDVALUE(_Dim_Date[Annee])",
            "lineageTag": "13e5910c-aa0a-4680-a919-772bd453b8a1"
          },
          {
            "name": "Extraction",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "Visuels & titres",
            "expression": [
              "\"Extraction vers :  \"",
              "                    & SWITCH( SELECTEDVALUE(Choix_CAT_CLT_REG[Choix_CAT_CLT_REG Commande])",
              "                        ,0,\"Catégories\"",
              "                        ,1,\"Clients\"",
              "                        ,2,\"Régions\")"
            ],
            "lineageTag": "5ee66638-c8c2-4ad8-b99f-b44cf08ecc7b"
          },
          {
            "name": "Titre_P1_A1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "            \"Analyse des volumes et chiffres d'affaire par \" ",
              "            & SWITCH( SELECTEDVALUE(Choix_CAT_CLT_REG[Choix_CAT_CLT_REG Commande])",
              "                        ,0,\"Catégories\"",
              "                        ,1,\"Clients\"",
              "                        ,2,\"Régions\")",
              "            & \" sur l'année \"",
              "            & SELECTEDVALUE(_Dim_Date[Annee])"
            ],
            "lineageTag": "ee6e839e-cf32-4b54-84e7-31e785e11118"
          },
          {
            "name": "Arrow_up",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "VAR _CA_M1= CALCULATE([CA],PREVIOUSMONTH(_Dim_Date[Date]))",
              "return",
              "IF([CA]>[CA_N-1],[CA]+10000,[CA_N-1]+10000)"
            ],
            "lineageTag": "a06c92ca-86ca-4af5-9d18-0b204092eda3"
          },
          {
            "name": "Arrow_CA_UP",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "IF([CA]>[CA_N-1],[CA]+10000,[CA_N-1]+10000)"
            ],
            "lineageTag": "2bf87dcc-0a94-445b-b5ca-870d627f894f"
          },
          {
            "name": "Arrow_CA_UP_ligne",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "IF([CA]>[CA_N-1],[CA]+10000,BLANK())"
            ],
            "lineageTag": "b1e44996-d09e-48a7-bf83-2ac5b30485f4"
          },
          {
            "name": "Arrow_CA_DOWN_ligne",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "IF([CA_N-1]>[CA],[CA_N-1]+10000,BLANK())"
            ],
            "lineageTag": "fa024474-c59f-4f19-ae26-219557c003d2"
          },
          {
            "name": "Null",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "0",
            "lineageTag": "20ea58eb-02af-4a1c-a0f3-da63be93d0c0"
          },
          {
            "name": "Github_test",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "\"Finalement il fait trop froid\"",
            "lineageTag": "f7577484-ec38-4d78-81d6-400f7e02c5d8"
          }
        ],
        "partitions": [
          {
            "name": "_Mesures-21c847b1-dc63-463f-b0bd-d178fc7756e6",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlCKjQUA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Colonne 1\" = _t]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(Source,{{\"Colonne 1\", Int64.Type}}),",
                "    #\"Colonnes supprimées\" = Table.RemoveColumns(#\"Type modifié\",{\"Colonne 1\"})",
                "in",
                "    #\"Colonnes supprimées\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Choix Année",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "3f19dfba864d470788258487d7a47fe4"
          }
        ],
        "columns": [
          {
            "name": "Choix Année",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "df636b04-a85d-4d07-8616-1fabd362711e",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "d6353d1f-196a-4bc5-9da2-e6ca422607fe",
        "measures": [
          {
            "name": "Valeur Choix Année",
            "expression": "SELECTEDVALUE('Choix Année'[Choix Année], 2)",
            "formatString": "0",
            "lineageTag": "ec84bcc0-a833-4530-a52b-aeaa5fe95b19"
          }
        ],
        "partitions": [
          {
            "name": "Choix Année-499c40c9-6584-4d1b-8dbe-f26b36a2ea2e",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(0, 5, 1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Temps",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "Actual",
              "expression": "SELECTEDMEASURE()",
              "formatStringDefinition": {
                "expression": "SELECTEDMEASUREFORMATSTRING()"
              },
              "ordinal": 0
            },
            {
              "name": "N-1",
              "expression": "CALCULATE(SELECTEDMEASURE(),SAMEPERIODLASTYEAR(_Dim_Date[Date]))",
              "formatStringDefinition": {
                "expression": "SELECTEDMEASUREFORMATSTRING()"
              },
              "ordinal": 1
            },
            {
              "name": "Delta",
              "expression": [
                "VAR CA = SELECTEDMEASURE()",
                "VAR CAN1 = CALCULATE(SELECTEDMEASURE(),SAMEPERIODLASTYEAR(_Dim_Date[Date]))",
                "",
                "RETURN",
                "",
                "CA - CAN1"
              ],
              "formatStringDefinition": {
                "expression": "SELECTEDMEASUREFORMATSTRING()"
              },
              "ordinal": 2
            },
            {
              "name": "Evol",
              "expression": [
                "VAR CA = SELECTEDMEASURE()",
                "VAR CAN1 = CALCULATE(SELECTEDMEASURE(),SAMEPERIODLASTYEAR(_Dim_Date[Date]))",
                "",
                "RETURN",
                "",
                "DIVIDE( CA - CAN1 , CAN1 , BLANK())"
              ],
              "formatStringDefinition": {
                "expression": "\"0.0 %\""
              },
              "ordinal": 3
            }
          ]
        },
        "columns": [
          {
            "name": "Temps",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a22c4e5-9e60-42d1-a829-de54ebf97063",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "5c063f29-9cf1-4a1b-92eb-45d3c8cc6365",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "606cd563-33e3-4e47-8522-24a06f531985",
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Temps_Tri",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "N-1",
              "expression": [
                "IF( ",
                "ISFILTERED( Temps[Ordinal] )",
                ",SELECTEDMEASURE()",
                ",CALCULATE(SELECTEDMEASURE(), Temps[Temps]=\"N-1\")",
                ")",
                "",
                ""
              ],
              "ordinal": 1
            },
            {
              "name": "Delta",
              "expression": [
                "IF( ",
                "ISFILTERED( Temps[Ordinal] )",
                ",SELECTEDMEASURE()",
                ",CALCULATE(SELECTEDMEASURE(), Temps[Temps]=\"Delta\")",
                ")",
                ""
              ],
              "ordinal": 2
            },
            {
              "name": "Actual",
              "expression": [
                "IF( ",
                "ISFILTERED( Temps[Ordinal] )",
                ",SELECTEDMEASURE()",
                ",CALCULATE(SELECTEDMEASURE(), Temps[Temps]=\"Actual\")",
                ")",
                "",
                ""
              ],
              "ordinal": 0
            },
            {
              "name": "Evol",
              "expression": [
                "IF( ",
                "ISFILTERED( Temps[Ordinal] )",
                ",SELECTEDMEASURE()",
                ",CALCULATE(SELECTEDMEASURE(), Temps[Temps]=\"Evol\")",
                ")",
                ""
              ],
              "ordinal": 3
            }
          ],
          "precedence": 1
        },
        "columns": [
          {
            "name": "Tri",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d712b49-c135-4219-96fd-e0ce8bec6b13",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "3960d610-9504-41f0-9cb5-112f28ce00e6",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "854da123-8cea-4777-a2f7-3911f66be8f8",
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Choix_HTML_Rank",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Libelle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cecfa18f-f729-4884-b32a-e5be0217c0c4",
            "sourceColumn": "Libelle",
            "summarizeBy": "none"
          },
          {
            "name": "Tri",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fe717edb-c831-44c7-8428-f1a53c81cfa2",
            "sourceColumn": "Tri",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4ae27825-eb8e-4f6f-b724-2b948932cc56",
        "partitions": [
          {
            "name": "Choix_HTML_Rank",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WckwuKU3MUQgsSVXSUTJUitWBCzk7AkWMwCJ+uoZQFcZwPljaBMx1Sc0pSYQqMEUSASsxAwu4luXDLDFHCIAVWCjFxgIA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Libelle = _t, Tri = _t]),",
                "    #\"Type modifié1\" = Table.TransformColumnTypes(Source,{{\"Tri\", Int64.Type}}),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(#\"Type modifié1\",{{\"Libelle\", type text}})",
                "in",
                "    #\"Type modifié\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Choix_CAT_PDT_CLT",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Tables",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8c06a9d-a189-43d3-b682-fd76c901f49f",
            "sourceColumn": "Tables",
            "summarizeBy": "none"
          },
          {
            "name": "Colonnes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "12b5ddbc-c23c-474d-a20c-a3594a8a3613",
            "sourceColumn": "Colonnes",
            "summarizeBy": "none"
          },
          {
            "name": "Tri",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f92c5944-05f0-47cb-ab72-9d702650f17d",
            "sourceColumn": "Tri",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "222622c9-af5d-44b2-b2f6-a2350f92efaf",
        "partitions": [
          {
            "name": "Choix_CAT_PDT_CLT",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45Wck4sSU3PL8pMLVbSQeJEQ5mVfom5qbFAKUOlWJ1opYCi/JTSzBKQWhgzGsxILoEpNAIrdM7JTM0Dq4Oyop3zcwsS8+DmGSvFxgIA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Tables = _t, Colonnes = _t, Tri = _t]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(Source,{{\"Tables\", type text}, {\"Colonnes\", type text}, {\"Tri\", Int64.Type}})",
                "in",
                "    #\"Type modifié\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Table_couleurs",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "CAT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d88ef239-ed20-42a3-ac2c-0f89b8a37271",
            "sourceColumn": "CAT",
            "summarizeBy": "none"
          },
          {
            "name": "Code_couleur",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "630648a4-4229-41a7-893a-7ccb711d7b49",
            "sourceColumn": "Code_couleur",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2757cb54-6497-4158-abf2-99dbc569c6ae",
        "partitions": [
          {
            "name": "Table_couleurs",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"VY2xDoIwFEV/pakrCaWEIqMWcNKYmLAgQ6UP06S2SQv/LzxcXM+9596+p2dvYvQu0oQeTiUrck6HpKf34PVi5kisMrOBgPlUTPw1Yl5DjBBmpFyvHGlnlNNAngtjXJDOr7K1gC7oF1PH/+21ahW5QthnSiEEFqR32nzAzZv5DgAOcRvQesCIi1Ur82YXLkEZF0lKJARQv8csE6La81sqN8Kyqm5KOgxf\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [CAT = _t, Code_couleur = _t]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(Source,{{\"CAT\", type text}, {\"Code_couleur\", type text}})",
                "in",
                "    #\"Type modifié\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Colour",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "New Calculation",
              "expression": "[CA]",
              "formatStringDefinition": {
                "expression": [
                  "VAR _CAT = LOOKUPVALUE(Table_couleurs[CAT],Table_couleurs[CAT],SELECTEDVALUE(Categories[CategoryName]),\"N/C\")",
                  "VAR _tableCouleurs = FILTER(Table_couleurs,[CAT]=_CAT)",
                  "RETURN",
                  "                MAXX(",
                  "                    _tableCouleurs,",
                  "                    [code_couleur]",
                  "                    )"
                ]
              }
            }
          ],
          "precedence": 2
        },
        "columns": [
          {
            "name": "Colours",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41f03edb-72cf-4aac-8062-61762e640570",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "b5d60f40-d397-488e-8044-1c83d1cffa0d",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "923e5c4b-1b4a-4fce-a635-33d5cabe6fb8",
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Z_PY🐍_Produits",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3c29666f-b073-45be-807f-d43991986a25",
            "sourceColumn": "ProductID",
            "summarizeBy": "none"
          },
          {
            "name": "ProductName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "63a8a285-6831-43d2-a4aa-631277dc548a",
            "sourceColumn": "ProductName",
            "summarizeBy": "none"
          },
          {
            "name": "SupplierID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cb35d103-bd3c-42c9-8fe8-8614603e6a11",
            "sourceColumn": "SupplierID",
            "summarizeBy": "none"
          },
          {
            "name": "CategoryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7b55bb5c-9202-4d1e-8ba2-683f6cd1d144",
            "sourceColumn": "CategoryID",
            "summarizeBy": "none"
          },
          {
            "name": "QuantityPerUnit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8a48aa7-60bc-4004-91ae-2cfc32e34bee",
            "sourceColumn": "QuantityPerUnit",
            "summarizeBy": "none"
          },
          {
            "name": "UnitPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34ca9c7c-7a5c-4521-9e34-c9f67771851d",
            "sourceColumn": "UnitPrice",
            "summarizeBy": "none"
          },
          {
            "name": "Fichier",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a30972c8-a51a-4e43-818a-b21836d35d8f",
            "sourceColumn": "Fichier",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bc20a778-e2b7-4901-932b-51526086bc03",
        "partitions": [
          {
            "name": "Z_PY🐍_Produits",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Python.Execute(\"import pandas as pd#(lf)df = pd.read_excel(r\"\"C:\\Users\\Frédéric ROUCHER\\OneDrive - KPI Consulting\\Bureau\\DATASET\\Dimensions.xlsx\"\", sheet_name=\"\"Produits\"\")\"),",
                "    df1 = Source{[Name=\"df\"]}[Value],",
                "    #\"Type modifié\" = Table.TransformColumnTypes(df1,{{\"ProductID\", Int64.Type}, {\"ProductName\", type text}, {\"SupplierID\", Int64.Type}, {\"CategoryID\", Int64.Type}, {\"QuantityPerUnit\", type text}, {\"UnitPrice\", type text}, {\"Fichier\", type text}})",
                "in",
                "    #\"Type modifié\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Z_PY🐍_Categories",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "CategoryID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3f64b13f-0ce9-4b25-804a-25b1bfc8980c",
            "sourceColumn": "CategoryID",
            "summarizeBy": "none"
          },
          {
            "name": "CategoryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "be1ca61e-419c-4a4f-afa6-2a452ac6a7a2",
            "sourceColumn": "CategoryName",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58767f29-aef5-4c41-8402-ca7919414df0",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "Picture",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6d898cb4-c431-44f1-aa76-de3701e5791d",
            "sourceColumn": "Picture",
            "summarizeBy": "none"
          },
          {
            "name": "Regroupement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aee43764-e535-4397-b8e0-b1002df255a3",
            "sourceColumn": "Regroupement",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "59329d9e-0f5f-49c4-a467-2fd34e2eb17b",
        "partitions": [
          {
            "name": "Z_PY🐍_Categories",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Python.Execute(\"import pandas as pd#(lf)df = pd.read_excel(r\"\"C:\\Users\\Frédéric ROUCHER\\OneDrive - KPI Consulting\\Bureau\\DATASET\\Dimensions.xlsx\"\", sheet_name=\"\"Categories\"\")\"),",
                "    df1 = Source{[Name=\"df\"]}[Value],",
                "    #\"Type modifié\" = Table.TransformColumnTypes(df1,{{\"CategoryID\", Int64.Type}, {\"CategoryName\", type text}, {\"Description\", type text}, {\"Picture\", type text}, {\"Regroupement\", type text}})",
                "in",
                "    #\"Type modifié\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Z_PY🐍_Employes",
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "EmployeeID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "52e83b65-c617-4de3-93a9-f9f2ed128efd",
            "sourceColumn": "EmployeeID",
            "summarizeBy": "count"
          },
          {
            "name": "LastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d629fad6-245a-4bd9-964a-c416735d097e",
            "sourceColumn": "LastName",
            "summarizeBy": "none"
          },
          {
            "name": "FirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "794909ae-5389-4e33-b718-d74ca716e49f",
            "sourceColumn": "FirstName",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "55f285c9-9535-41b6-9a92-13e79fe288da",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          },
          {
            "name": "TitleOfCourtesy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cea7e3d3-e0ba-4ec3-a5d8-a501bbe322d3",
            "sourceColumn": "TitleOfCourtesy",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8fd95909-20a1-420c-bfe1-8056318ac5aa",
        "partitions": [
          {
            "name": "Z_PY🐍_Employes",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Python.Execute(\"import pandas as pd#(lf)df = pd.read_excel(r\"\"C:\\Users\\Frédéric ROUCHER\\OneDrive - KPI Consulting\\Bureau\\DATASET\\Dimensions.xlsx\"\", sheet_name=\"\"Employes\"\")\"),",
                "    df1 = Source{[Name=\"df\"]}[Value],",
                "    #\"Type modifié\" = Table.TransformColumnTypes(df1,{{\"EmployeeID\", Int64.Type}, {\"LastName\", type text}, {\"FirstName\", type text}, {\"Title\", type text}, {\"TitleOfCourtesy\", type text}})",
                "in",
                "    #\"Type modifié\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Z_PY🐍_Clients",
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "19391cf4-05ce-4f20-ba5a-637d3dacb5af",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none"
          },
          {
            "name": "CompanyName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d071737-bcd1-495b-9081-c057ecce7889",
            "sourceColumn": "CompanyName",
            "summarizeBy": "none"
          },
          {
            "name": "ContactName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35256efb-7594-4ce1-a512-3401ccb8da73",
            "sourceColumn": "ContactName",
            "summarizeBy": "none"
          },
          {
            "name": "ContactTitle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6417091a-f788-409c-90cf-0219f58ec2f2",
            "sourceColumn": "ContactTitle",
            "summarizeBy": "none"
          },
          {
            "name": "Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9643f8d3-27e8-45a8-b128-9682d50af6c1",
            "sourceColumn": "Address",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87db66a6-97f6-43ed-a475-ff7bff093f4b",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bebec562-8f3a-4218-8472-ce5651bdae46",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "PostalCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c0aa89a5-2df2-4cc9-932e-1bc28ed47e1c",
            "sourceColumn": "PostalCode",
            "summarizeBy": "count"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e54326db-c038-4155-966f-ffc01c05eb1e",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Phone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "caa344ff-c697-4cac-928f-f421ed3c0487",
            "sourceColumn": "Phone",
            "summarizeBy": "none"
          },
          {
            "name": "Fax",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "986bd84c-0f5d-4ea8-8c9a-2dbec7e18a64",
            "sourceColumn": "Fax",
            "summarizeBy": "none"
          },
          {
            "name": "Regroupement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1537555-e373-4109-a592-961fb4ab4221",
            "sourceColumn": "Regroupement",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "17f6d318-c398-4cd4-a6ca-c8729244d433",
        "partitions": [
          {
            "name": "Z_PY🐍_Clients",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Python.Execute(\"import pandas as pd#(lf)df = pd.read_excel(r\"\"C:\\Users\\Frédéric ROUCHER\\OneDrive - KPI Consulting\\Bureau\\DATASET\\Dimensions.xlsx\"\", sheet_name=\"\"Clients\"\")\"),",
                "    df1 = Source{[Name=\"df\"]}[Value],",
                "    #\"Type modifié\" = Table.TransformColumnTypes(df1,{{\"CustomerID\", type text}, {\"CompanyName\", type text}, {\"ContactName\", type text}, {\"ContactTitle\", type text}, {\"Address\", type text}, {\"City\", type text}, {\"Region\", Int64.Type}, {\"PostalCode\", Int64.Type}, {\"Country\", type text}, {\"Phone\", type text}, {\"Fax\", type text}, {\"Regroupement\", type text}})",
                "in",
                "    #\"Type modifié\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Z_PY🐍_Fournisseurs",
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "SupplierID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c81cd5fe-dcaf-4d93-a655-be7d50399e2b",
            "sourceColumn": "SupplierID",
            "summarizeBy": "none"
          },
          {
            "name": "CompanyName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2dac33b6-7d01-4f5b-83fc-1d8d5fda5d0a",
            "sourceColumn": "CompanyName",
            "summarizeBy": "none"
          },
          {
            "name": "ContactName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0ad4f3f-5e90-4833-b13c-1ca5c5433999",
            "sourceColumn": "ContactName",
            "summarizeBy": "none"
          },
          {
            "name": "ContactTitle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7c2fbb0-0b35-4837-98e7-1320ae4b46e7",
            "sourceColumn": "ContactTitle",
            "summarizeBy": "none"
          },
          {
            "name": "Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46ae1674-b41d-4d3d-a6c0-25bcfd221df3",
            "sourceColumn": "Address",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f72a6576-1ba7-4e7a-9aa5-8fe76d6d1a51",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e18b585d-c3ad-4a1c-97d3-db8e0c77a914",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "PostalCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c8d1508-ab0f-4219-bcbc-a111722f7c9e",
            "sourceColumn": "PostalCode",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae201a69-280a-4b00-ad49-1c9b6c60f972",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Phone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d0f2dd2-d4c7-414f-ae7c-d7fe4cc6a0e8",
            "sourceColumn": "Phone",
            "summarizeBy": "none"
          },
          {
            "name": "Fax",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "261b6c6c-8d99-498b-80a8-15ab43c4e987",
            "sourceColumn": "Fax",
            "summarizeBy": "none"
          },
          {
            "name": "HomePage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "819c00fe-0464-46fd-b206-bd550aa19803",
            "sourceColumn": "HomePage",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "eb95bd33-f72b-45f3-8667-f672e6253d65",
        "partitions": [
          {
            "name": "Z_PY🐍_Fournisseurs",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Python.Execute(\"import pandas as pd#(lf)df = pd.read_excel(r\"\"C:\\Users\\Frédéric ROUCHER\\OneDrive - KPI Consulting\\Bureau\\DATASET\\Dimensions.xlsx\"\", sheet_name=\"\"Fournisseurs\"\")\"),",
                "    df1 = Source{[Name=\"df\"]}[Value]",
                "in",
                "    df1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Z_PY🐍_Region",
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "columns": [
          {
            "name": "Code_region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02f7692b-7f71-458d-85e8-519747fdcc2d",
            "sourceColumn": "Code_region",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "904eb0ab-1ea0-4508-83d9-78b10b3f926e",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8c5d33a2-0f98-4371-8792-57faf74453a8",
        "partitions": [
          {
            "name": "Z_PY🐍_Region",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Python.Execute(\"import pandas as pd#(lf)df = pd.read_excel(r\"\"C:\\Users\\Frédéric ROUCHER\\OneDrive - KPI Consulting\\Bureau\\DATASET\\Dimensions.xlsx\"\", sheet_name=\"\"Region\"\")#(lf)df2 = pd.read_excel(r\"\"C:\\Users\\Frédéric ROUCHER\\OneDrive - KPI Consulting\\Bureau\\DATASET\\Dimensions.xlsx\"\", sheet_name=\"\"Clients\"\")\"),",
                "    df1 = Source{[Name=\"df\"]}[Value]",
                "in",
                "    df1"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Z_PY🐍_Detail_Commandes",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "OrderID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "56ca8a9b-5d64-431f-a0c1-a98191fc9f34",
            "sourceColumn": "OrderID",
            "summarizeBy": "count"
          },
          {
            "name": "ProductID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6f74f474-3305-43bb-a50a-c9f6245dcfca",
            "sourceColumn": "ProductID",
            "summarizeBy": "none"
          },
          {
            "name": "UnitPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5756c657-d7a2-40f3-aeec-b4f014eb8f27",
            "sourceColumn": "UnitPrice",
            "summarizeBy": "sum"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4613f5b3-abc3-4089-a17e-ba69bc4a0f7f",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "0fcd6c3a-6cbd-4df7-8b6f-720e3ad46352",
        "partitions": [
          {
            "name": "Z_PY🐍_Detail_Commandes",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Python.Execute(\"import pandas as pd#(lf)Detail_Commandes = pd.read_excel(r\"\"C:\\Users\\Frédéric ROUCHER\\OneDrive - KPI Consulting\\Bureau\\DATASET\\Detail_Commandes.xlsx\"\", sheet_name=\"\"Detail_Commande\"\", dtype = str)#(lf)# Selection des colonnes :#(lf)Colonnes = [\"\"OrderID\"\",\"\"ProductID\"\",\"\"UnitPrice\"\",\"\"Quantity\"\"]#(lf)Detail_Commandes = Detail_Commandes[Colonnes]#(lf)# Remplacement . par ,:#(lf)Detail_Commandes[\"\"UnitPrice\"\"] = Detail_Commandes[\"\"UnitPrice\"\"].str.replace(\"\".\"\",\"\",\"\")#(lf)#(lf)                \"),",
                "    Detail_Commandes1 = Source{[Name=\"Detail_Commandes\"]}[Value],",
                "    #\"Type modifié\" = Table.TransformColumnTypes(Detail_Commandes1,{{\"OrderID\", Int64.Type}, {\"ProductID\", Int64.Type}, {\"UnitPrice\", type number}, {\"Quantity\", Int64.Type}})",
                "in",
                "    #\"Type modifié\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Measure",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "CA",
              "expression": "[CA]"
            },
            {
              "name": "QTE",
              "expression": "[Qte]"
            }
          ],
          "precedence": 3
        },
        "columns": [
          {
            "name": "Tri",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6eb2c01c-dde4-4602-8326-94b31ae3f699",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "bc1aca66-447e-44dc-ba04-d356603852be",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "950e742d-f3ee-41e1-aa1e-ef0ca3e7a78c",
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Mesure_Tri",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "CA",
              "expression": [
                "IF( ",
                "ISFILTERED( Mesure_tri[Ordinal] )",
                ",SELECTEDMEASURE()",
                ",CALCULATE(SELECTEDMEASURE(), Mesure_tri[Tri]=\"CA\")",
                ")"
              ],
              "ordinal": 1
            },
            {
              "name": "Qte",
              "expression": [
                "IF( ",
                "ISFILTERED( Mesure_tri[Ordinal] )",
                ",SELECTEDMEASURE()",
                ",CALCULATE(SELECTEDMEASURE(), Mesure_tri[Tri]=\"QTE\")",
                ")"
              ],
              "ordinal": 0
            }
          ],
          "precedence": 4
        },
        "columns": [
          {
            "name": "Tri",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "930a32b7-110e-4e60-aa42-2d81404d1248",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "42534412-19d1-49cb-aeef-24bb0d9ea994",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "e910f439-f9ad-4766-89c2-9b79a7971507",
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Choix_CAT_CLT_REG",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "7e021f49ad48410f990886d648d804cd"
          }
        ],
        "columns": [
          {
            "name": "Choix_CAT_CLT_REG",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "0d369a83-75f4-432b-8bdc-65a157bda891",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Choix_CAT_CLT_REG Champs"
                }
              ]
            },
            "sortByColumn": "Choix_CAT_CLT_REG Commande",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Choix_CAT_CLT_REG Champs",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "9f762763-c856-49d7-aaa9-6c1411b1c55e",
            "sortByColumn": "Choix_CAT_CLT_REG Commande",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Choix_CAT_CLT_REG Commande",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "a43708b5-a9ae-489f-83dd-1b3606ca8567",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "1ad45d60-1f6b-4a9d-a6a7-4563a750a682",
        "partitions": [
          {
            "name": "Choix_CAT_CLT_REG",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Catégories\", NAMEOF('Categories'[CategoryName]), 0),",
                "    (\"Clients\", NAMEOF('Clients'[CompanyName]), 1),",
                "    (\"Régions\", NAMEOF('Region'[Region]), 2)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Blank_Html",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Libelle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e23ff85-355d-4f8a-b760-4480b982a3b0",
            "sourceColumn": "Libelle",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7009acb7-dd8a-4f25-af75-1473953ab31c",
        "partitions": [
          {
            "name": "Blank_Html",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Libelle = _t]),",
                "    #\"Type modifié\" = Table.TransformColumnTypes(Source,{{\"Libelle\", type text}})",
                "in",
                "    #\"Type modifié\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Groupe de calcul",
        "calculationGroup": {
          "precedence": 5
        },
        "columns": [
          {
            "name": "Colonne du groupe de calcul",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab218105-c180-4f00-ba36-f09347035329",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d469e8d0-b2dc-419d-a236-7e6df3f3b672",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "b5567b5e-0d31-474e-946d-41bd27d22f35",
        "partitions": [
          {
            "name": "Groupe de calcul",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Test_github",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "TestA",
              "expression": "SELECTEDMEASURE()"
            },
            {
              "name": "TestB",
              "expression": "SELECTEDMEASURE()"
            }
          ],
          "precedence": 6
        },
        "columns": [
          {
            "name": "Test1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "55477ecb-d9a0-4ab7-bd07-7168f74921bc",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Ordinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4086c494-24ba-4272-beff-4d3cb8a48f68",
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "47a3e275-1ad7-46b1-88ad-b208f4bc86b5",
        "partitions": [
          {
            "name": "Test_github",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Test2_tabular_editor",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "New Calculation",
              "expression": "selectedmeasure()"
            }
          ],
          "precedence": 7
        },
        "columns": [
          {
            "name": "Tabular",
            "dataType": "string",
            "lineageTag": "6a0b2d28-2d1b-48ad-a507-313570123f86",
            "sortByColumn": "Ordinal",
            "sourceColumn": "Name"
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "fd6bf233-7977-4b49-9401-caa8af0d377f",
            "sourceColumn": "Ordinal"
          }
        ],
        "lineageTag": "36a248f2-4e23-46b7-bc64-64fc6fc6f7e5",
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      }
    ]
  }
}